### ISSUE TITLE
Save Word To Database Exception

### ISSUE THREAD

**Issue by Ghost-Sailor** [ochensati/CircularEditor2#1]
Error is as follows: "Unhandled exception has occured in your application [...]
Type: 'System.Windows.Forms.PictureBox' in Assembly
'System.Windows.Forms, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089' is not marked as serializable."

**Comment by ochensati** [comment]
Save has been fixed to allow image saves
